[package]
name = "series-troxide"
authors = ["Maarifa Maarifa"]
license = "GPL-3.0"
description = "A modern Series Tracker"
categories = ["series", "TV"]
keywords = ["series-tracker", "tv-shows", "tv-series"]
repository = "https://github.com/MaarifaMaarifa/series-troxide"
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
iced = { version = "0.9.0", features = ["image", "svg", "tokio"] }
iced_aw = { version = "0.5.2", features = ["spinner"] }
anyhow = "1"
thiserror = "1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.7.4"
json = "0.12.4"
tokio = { version = "1.28.1", features = ["full"] }
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
sled = "0.34.7"
bincode = "1.3.3"
rand = "0.8.5"
indexmap = { version = "1.9.3", features = ["serde"] }
directories = "5.0.1"
lazy_static = "1.4.0"
sha2 = "0.10.7"
chrono = { version = "0.4.26", features = ["serde"] }
html2text = "0.6.0"
bytes = "1.4.0"
rfd = "0.11.4"
rust_iso3166 = "0.1.10"

[build-dependencies]
built = { version = "0.6.1", features = ["git2", "chrono"] }

[profile.release]
lto = true
strip = true
codegen-units = 1
