[package]
name = "series-troxide"
authors = ["Maarifa Maarifa"]
description = "A Series Tracker"
categories = ["series", "TV"]
repository = "https://github.com/MaarifaMaarifa/series-troxide"
version = "0.0.2"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
