[package]
name = "series-troxide"
authors = ["Maarifa Maarifa"]
description = "A Series Tracker"
categories = ["series", "TV"]
repository = "https://github.com/MaarifaMaarifa/series-troxide"
version = "0.0.2"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
iced = { version = "0.9.0", features = ["image", "svg", "tokio"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tokio = { version = "1.28.1", features = ["full"] }
json = "0.12.4"
rand = "0.8.5"
indexmap = { version = "1.9.3", features = ["serde"] }
directories = "5.0.1"
toml = "0.7.4"
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
sled = "0.34.7"
bincode = "1.3.3"
lazy_static = "1.4.0"

[profile.release]
lto = true
strip = true
codegen-units = 1
