name: Build

on: 
  push:
    branches: [ '**' ]

jobs:
  release:
    name: ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: code-editor
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: code-editor
            command: both

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: code-editor.exe
            command: both

            # more release targets here ...

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name:  Install
        run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt update
              sudo apt install -y libgtk-3-dev librust-atk-dev 
         fi
        shell: bash

      - uses: Swatinem/rust-cache@v2

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-editor-${{ matrix.platform.target }}
          path: ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}