name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings -C opt-level=0"

jobs:

  test:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  build:
    name: Run build
    uses: ./.github/workflows/run-build.yml
  
