name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  # since opt-level of 3 is used for dependencies in dev profile as
  # configured through Cargo.toml, we explicitly set it to 0
  RUSTFLAGS: -Dwarnings -C opt-level=0

jobs:

  test:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  build:
    name: Run build
    uses: ./.github/workflows/run-build.yml
  
