name: Run Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: installing libgtk-3-dev (rfd crate dependency)
        if: matrix.os== 'ubuntu-latest,'
        run: sudo apt update && sudo apt install libgtk-3-dev

      - name: Cache setup
        uses: Swatinem/rust-cache@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
            command: build        
 
