name: Run Build

on:
  workflow_call:

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: apt update
        run: sudo apt update

      - name: installing libgtk-3-dev (rfd crate dependency)
        run: sudo apt libgtk-3-dev

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
            command: build
