name: Run Tests and Linters

on:
  workflow_call:

jobs:
  fmt:
    name: Run rustfmt in check mode
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
            command: fmt
            args: -- --check

  clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: apt update
        run: sudo apt update

      - name: installing libgtk-3-dev (rfd crate dependency)
        run: sudo apt install libgtk-3-dev
      
      - name: Cache setup
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
            command: clippy
            args: -- -D warnings

  spell-check:
    name: Run spell check
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: checking for typos
        uses: crate-ci/typos@v1.27.3

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: apt update
        run: sudo apt update

      - name: installing libgtk-3-dev (rfd crate dependency)
        run: sudo apt install libgtk-3-dev

      - name: Cache setup
        uses: Swatinem/rust-cache@v2

      - name: Run test
        uses: actions-rs/cargo@v1
        with:
            command: test
