name: Run Build

on:
  workflow_call:

jobs:
  x86_64-unknown-linux-gnu-build:
    name: Run build (x86_64-unknown-linux-gnu)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: apt update
        run: sudo apt update

      - name: installing libgtk-3-dev (rfd crate dependency)
        run: sudo apt install libgtk-3-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
            command: build        
            args: --target x86_64-unknown-linux-gnu

  x86_64-pc-windows-gnu-build:
    name: Run build (x86_64-pc-windows-gnu)
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: apt update
        run: sudo apt update

      - name: installing libgtk-3-dev (rfd crate dependency)
        run: sudo apt install libgtk-3-dev

      - name: installing mingw-w64
        run: sudo apt install mingw-w64
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Set target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
            command: build        
            args: --target x86_64-pc-windows-gnu

  windows-build:
    name: Run build (windows)
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
            command: build

  macos-build:
    name: Run build (macos)
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
            command: build
